name: CI
on:
  push:
    branches: [ "**" ]
jobs:
  continuous:
    name: Execute CI Pipeline
    runs-on: ubuntu-latest
    steps:
    - name: Checkout Code
      uses: actions/checkout@v6
    - name: Setup Env
      uses: ./.github/actions/setup-env
    - name: Run Tests
      run: ./gradlew test
