name: Release
on:
  workflow_dispatch:
    inputs:
      version:
        description: 'Release version (2026.X.Y)'
        required: true
        type: string
permissions: # keep this at the root level, despite any warnings about placement!
  contents: write  # required to create releases
jobs:
  release:
    name: Create new Release
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v6
      - name: Setup Env
        uses: ./.github/actions/setup-env
      - name: Update version number
        run: echo ${{ inputs.version }} > version.txt
      - name: Gradle Build
        run: ./gradlew test build
      - name: Commit version update
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add version.txt
          git commit -m "Update version to ${{ inputs.version }}"
          git push origin HEAD:main
      - name: Gradle Publish
        run: ./gradlew publish
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Create GIT Tag
        uses: negz/create-tag@v1
        with:
          version: ${{ inputs.version }}
          message: tag version ${{ inputs.version }}
          token: ${{ secrets.GITHUB_TOKEN }}
      - name: Create GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: ${{ inputs.version }}
          name: Release ${{ inputs.version }}
          body: |
            Get the JAR from https://jitpack.io/#seepick/usc-client/${{ inputs.version }}
          draft: false
          prerelease: false
